server:
  port: 9007

spring:
  cors:
    allowed-origins: "http://localhost:5173"  # El origen permitido para CORS (ajústalo según tu entorno)
    allowed-methods: "GET,POST,PUT,DELETE"     # Métodos HTTP permitidos
    allowed-headers: "*"                       # Todas las cabeceras permitidas (ajústalo según tus necesidades)
    allow-credentials: true   
  application:
    name: ProjectTasf-
  devtools:
    restart:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5433/prueba-one
    username:  #usuario base de datos
    password:  #contrasena base de datos
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    time-zone: America/Bogota
    locale: es-Co
  logging:
    file:
      path: ./logs/
    pattern.file: '%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M - %msg%n'
    logback:
      rolling policy:
        max-file-size: 10MB
        max-history: 0

